export const GET_ALLSLOT_REQUEST = 'GET_ALLSLOT_REQUEST'
export const GET_ALLSLOT_SUCCESS = 'GET_ALLSLOT_SUCCESS'
export const GET_ALLSLOT_ERROR = 'GET_ALLSLOT_ERROR'

export const GET_DATEDATA_REQUEST = 'GET_DATEDATA_REQUEST'
export const GET_DATEDATA_SUCCESS = 'GET_DATEDATA_SUCCESS'
export const GET_DATEDATA_ERROR = 'GET_DATEDATA_ERROR'
